### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by yukkysaito** [brNX/ros_mpu6050_node#2]
I want to know how to use this node.
I have a arduino, raspberry pi, mbed and MPU6050.
I wanna run MPU6050 as a ROS node.

**Comment by brNX** [comment]
Hi , sorry this code is unmaintaned , I used it a long time ago with a mpu6050 and a hmc5883l  compass.

If you have an arduino you can maybe try this : https://github.com/fsteinhardt/mpu6050_serial_to_imu

Regards

**Comment by yukkysaito** [comment]
Thank you!
